name: Publish npm packages

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Release type'
                required: true
                type: choice
                default: 'development'
                options:
                    - development
                    - latest
                    - bugfix
                    - wp
            wp_version:
                description: 'WordPress major version (`wp` only)'
                type: string

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    release:
        name: Release - ${{ github.event.inputs.release_type }}
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
        environment: WordPress packages
        steps:
            - name: Checkout (for CLI)
              if: ${{ github.event.inputs.release_type != 'wp' }}
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  path: cli
                  ref: trunk
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Checkout (for publishing)
              if: ${{ github.event.inputs.release_type != 'wp' }}
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  path: publish
                  # Later, we switch this branch in the script that publishes packages.
                  ref: trunk
                  token: ${{ secrets.GUTENBERG_TOKEN }}
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: true

            - name: Checkout (for publishing WP major version)
              if: ${{ github.event.inputs.release_type == 'wp' && github.event.inputs.wp_version }}
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  path: publish
                  ref: wp/${{ github.event.inputs.wp_version }}
                  # We need to ensure that Lerna can read the commit created during the previous npm publishing.
                  # Lerna assumes that all packages need publishing if it can't access the necessary information.
                  fetch-depth: 999
                  token: ${{ secrets.GUTENBERG_TOKEN }}
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: true

            - name: Configure git user name and email (for publishing)
              run: |
                  cd publish
                  git config user.name "Gutenberg Repository Automation"
                  git config user.email gutenberg@wordpress.org

            - name: Setup Node.js
              if: ${{ github.event.inputs.release_type != 'wp' }}
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                  node-version-file: 'cli/.nvmrc'
                  registry-url: 'https://registry.npmjs.org'
                  check-latest: true

            - name: Setup Node.js (for WP major version)
              if: ${{ github.event.inputs.release_type == 'wp' && github.event.inputs.wp_version }}
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                  node-version-file: 'publish/.nvmrc'
                  registry-url: 'https://registry.npmjs.org'
                  check-latest: true

            - name: Publish development packages to npm ("next" dist-tag)
              if: ${{ github.event.inputs.release_type == 'development' }}
              run: |
                  cd cli
                  npm ci
                  ./bin/plugin/cli.js npm-next --ci --repository-path ../publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish packages based on the latest Gutenberg plugin to npm ("latest" dist-tag)
              if: ${{ github.event.inputs.release_type == 'latest' }}
              run: |
                  cd cli
                  npm ci
                  ./bin/plugin/cli.js npm-latest --semver minor --ci --repository-path ../publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish packages to npm with bug fixes ("latest" dist-tag)
              if: ${{ github.event.inputs.release_type == 'bugfix' }}
              run: |
                  cd cli
                  npm ci
                  ./bin/plugin/cli.js npm-bugfix --ci --repository-path ../publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish packages to npm for WP major version ("wp/${{ github.event.inputs.wp_version || 'X.Y' }}" dist-tag)
              if: ${{ github.event.inputs.release_type == 'wp' && github.event.inputs.wp_version }}
              run: |
                  cd publish
                  npm ci
                  npx lerna publish patch --dist-tag "wp-$WP_VERSION" --no-private --yes --no-verify-access
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  WP_VERSION: ${{ github.event.inputs.wp_version }}
